<?php
/* THIS IS A GENERATED FILE. DO NOT EDIT DIRECTLY. */
$wp_ai_tools_plugin_i18n_strings = array(
__( 'Nothing here yet', 'sg-ai-studio' ),
__( '%(fromItem)d-%(toItem)d of %(totalItems)d', 'sg-ai-studio' ),
__( 'Go to first page', 'sg-ai-studio' ),
__( 'Go to previous page', 'sg-ai-studio' ),
__( 'Go to next page', 'sg-ai-studio' ),
__( 'Go to last page', 'sg-ai-studio' ),
__( 'Read this post', 'sg-ai-studio' ),
__( 'Active', 'sg-ai-studio' ),
__( 'Inactive', 'sg-ai-studio' ),
__( 'SiteGround AI Connector', 'sg-ai-studio' ),
__( 'Use your SiteGround AI Studio tokens to run every AI functionality powered by the WordPress', 'sg-ai-studio' ),
__( 'AI plugin', 'sg-ai-studio' ),
__( 'or any other plugin using the Connectors framework.', 'sg-ai-studio' ),
__( 'Learn More.', 'sg-ai-studio' ),
__( 'Use SiteGround AI for all WordPress AI features', 'sg-ai-studio' ),
__( 'Recommended', 'sg-ai-studio' ),
__( 'Use SiteGround AI for AI Agent functionalities only', 'sg-ai-studio' ),
__( 'Active', 'sg-ai-studio' ),
__( 'Inactive', 'sg-ai-studio' ),
__( 'AI Agent by SiteGround', 'sg-ai-studio' ),
__( 'Connected', 'sg-ai-studio' ),
__( 'Delegate entire processes to AI - build site architecture with menus, restructure taxonomies, run seasonal promotions, and other complex tasks. Manage your WordPress and WooCommerce sites through a simple chat with AI Agent by SiteGround.', 'sg-ai-studio' ),
__( 'Open chat', 'sg-ai-studio' ),
__( 'Dashboard banner', 'sg-ai-studio' ),
__( 'When this option is on, you will see the AI Agent listed in the editing options of some of the standard blocks of the Gutenberg Block Editor. This allows you to easily use AI for creating and editing text and images in your posts. If the option is turned off, you will not see the AI editing option in the blocks, but you can still use the general AI Agent chat and the custom AI Content Generator block.', 'sg-ai-studio' ),
__( 'AI Editing in Gutenberg Blocks', 'sg-ai-studio' ),
__( 'Active', 'sg-ai-studio' ),
__( 'Inactive', 'sg-ai-studio' ),
__( 'AI Agent Plugin', 'sg-ai-studio' ),
__( 'Connected', 'sg-ai-studio' ),
__( 'Your plugin is active and connected - a two-way bridge between your WordPress site and SiteGround AI Studio.', 'sg-ai-studio' ),
__( 'Disconnect', 'sg-ai-studio' ),
__( "To protect your website from accidental or harmful changes, the AI Agent for WordPress includes a built-in safety option called \"Power Mode.\" Power Mode is disabled by default to ensure that high-impact actions cannot be executed accidentally. Actions that require you to enable Power Mode include deletions (users, posts, pages, files, etc.), bulk operations, global settings modifications, product, order, and price updates.", 'sg-ai-studio' ),
__( 'Learn More.', 'sg-ai-studio' ),
__( 'Power Mode', 'sg-ai-studio' ),
__( 'High impact', 'sg-ai-studio' ),
__( 'Active', 'sg-ai-studio' ),
__( 'Inactive', 'sg-ai-studio' ),
__( 'You also have active one-time token top-up(s).', 'sg-ai-studio' ),
__( 'remaining', 'sg-ai-studio' ),
__( 'AI Studio uses SiteGround Al Tokens. You currently have no active subscription. %(childBudget)s To subscribe or add more tokens click the Manage button.', 'sg-ai-studio' ),
__( 'AI Agent uses SiteGround AI Tokens. To see AI Tokens reset date(s) or add more tokens click the Add More Tokens button.', 'sg-ai-studio' ),
__( 'AI Agent uses SiteGround AI Tokens. To see AI Tokens reset date(s) or add more tokens click the Manage AI Tokens button.', 'sg-ai-studio' ),
__( 'AI Tokens', 'sg-ai-studio' ),
__( 'Open chat', 'sg-ai-studio' ),
__( 'Add more tokens', 'sg-ai-studio' ),
__( 'Manage AI Tokens', 'sg-ai-studio' ),
__( 'Admin chat bubble is visible', 'sg-ai-studio' ),
__( 'Admin chat bubble is hidden', 'sg-ai-studio' ),
__( 'Front-end chat bubble is visible', 'sg-ai-studio' ),
__( 'Front-end chat bubble is hidden', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again.', 'sg-ai-studio' ),
__( 'SiteGround AI Studio Connector is enabled', 'sg-ai-studio' ),
__( 'SiteGround AI Studio Connector is disabled', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again.', 'sg-ai-studio' ),
__( 'AI Editing in Gutenberg Blocks is enabled', 'sg-ai-studio' ),
__( 'AI Editing in Gutenberg Blocks is disabled', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again.', 'sg-ai-studio' ),
__( 'Activity', 'sg-ai-studio' ),
__( 'Details', 'sg-ai-studio' ),
__( 'Date', 'sg-ai-studio' ),
__( 'AI Agent by SiteGround - Activity & Usage', 'sg-ai-studio' ),
__( 'Tokens usage', 'sg-ai-studio' ),
__( 'Activity Log', 'sg-ai-studio' ),
__( 'All', 'sg-ai-studio' ),
__( 'Activity', 'sg-ai-studio' ),
__( 'Details', 'sg-ai-studio' ),
__( 'Date', 'sg-ai-studio' ),
__( 'Features', 'sg-ai-studio' ),
__( 'Go to settings', 'sg-ai-studio' ),
__( 'Power mode', 'sg-ai-studio' ),
__( 'Bulk actions • Global changes • Deletions', 'sg-ai-studio' ),
__( 'AI Editing in Gutenberg', 'sg-ai-studio' ),
__( 'Blocks • Texts • Images', 'sg-ai-studio' ),
__( 'Agent Appearance', 'sg-ai-studio' ),
__( 'Chat bubble • Admin & Front-end', 'sg-ai-studio' ),
__( 'Tokens usage', 'sg-ai-studio' ),
__( 'Recent Activity', 'sg-ai-studio' ),
__( 'View All', 'sg-ai-studio' ),
__( 'Recommended reads', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'AI Agent by SiteGround', 'sg-ai-studio' ),
__( 'To activate the plugin, you need to sign up for', 'sg-ai-studio' ),
__( 'SiteGround AI Studio service', 'sg-ai-studio' ),
__( 'and connect the plugin via a unique token. Websites hosted on SiteGround platform will be connected automatically.', 'sg-ai-studio' ),
__( 'Learn More.', 'sg-ai-studio' ),
__( 'Connect', 'sg-ai-studio' ),
__( 'Video preview', 'sg-ai-studio' ),
__( 'Pause video', 'sg-ai-studio' ),
__( 'Play video', 'sg-ai-studio' ),
__( 'AI Agent by SiteGround - Settings', 'sg-ai-studio' ),
__( 'Plugin Activation', 'sg-ai-studio' ),
__( 'Connector Settings', 'sg-ai-studio' ),
__( 'Features', 'sg-ai-studio' ),
__( 'Agent Appearance', 'sg-ai-studio' ),
__( 'Chat Bubble in WordPress Admin', 'sg-ai-studio' ),
__( 'Show the AI Agent chat bubble inside the WordPress admin area. Turn this off to hide the floating bubble.', 'sg-ai-studio' ),
__( 'Chat Bubble on Your Website (Front-End)', 'sg-ai-studio' ),
__( 'Show the AI Agent chat bubble on the logged-in front-end of your website. On by default for adminstrators only.', 'sg-ai-studio' ),
__( "Ask me anything WordPress related and I'll help.", 'sg-ai-studio' ),
__( 'How can I help you today?', 'sg-ai-studio' ),
__( 'Your WordPress AI Assistant. Ask about content, your store, speed, or security.', 'sg-ai-studio' ),
__( 'AI Agent by SiteGround', 'sg-ai-studio' ),
__( 'New chat', 'sg-ai-studio' ),
__( 'History', 'sg-ai-studio' ),
__( 'Minimize', 'sg-ai-studio' ),
__( 'Popover', 'sg-ai-studio' ),
__( 'Sidebar', 'sg-ai-studio' ),
__( 'Full Screen', 'sg-ai-studio' ),
__( 'View mode', 'sg-ai-studio' ),
__( 'Today', 'sg-ai-studio' ),
__( 'Last 7 Days', 'sg-ai-studio' ),
__( 'Last 30 Days', 'sg-ai-studio' ),
__( 'Older', 'sg-ai-studio' ),
__( 'Insufficient tokens. Please go to {{a}}SiteGround AI Studio{{/a}} to upgrade or add more tokens.', 'sg-ai-studio' ),
__( 'This conversation has grown too long. To continue, please start a new chat.', 'sg-ai-studio' ),
__( "Couldn't process the request. Please try again.", 'sg-ai-studio' ),
__( 'Retry', 'sg-ai-studio' ),
__( 'User uploaded image', 'sg-ai-studio' ),
__( 'User uploaded image', 'sg-ai-studio' ),
__( 'Image had been deleted', 'sg-ai-studio' ),
__( 'File has been deleted', 'sg-ai-studio' ),
__( 'Generated by %(model)s', 'sg-ai-studio' ),
__( 'Image had been deleted', 'sg-ai-studio' ),
__( 'Power Mode is on. Note: Power Mode may modify your site’s content or settings. Tap Learn more for details before proceeding.', 'sg-ai-studio' ),
__( 'Learn more', 'sg-ai-studio' ),
__( 'Enable Power Mode to continue. Note: Power Mode may modify your site’s content or settings. Tap Learn more for details before enabling.', 'sg-ai-studio' ),
__( 'Learn more', 'sg-ai-studio' ),
__( 'Enable', 'sg-ai-studio' ),
__( 'Done: %(label)s', 'sg-ai-studio' ),
__( 'Working on your site', 'sg-ai-studio' ),
__( 'Creating image', 'sg-ai-studio' ),
__( 'Searching the web', 'sg-ai-studio' ),
__( 'Reading', 'sg-ai-studio' ),
__( 'Calculating', 'sg-ai-studio' ),
__( 'Thinking', 'sg-ai-studio' ),
__( 'Generate content & images', 'sg-ai-studio' ),
__( 'Install, update & audit plugins', 'sg-ai-studio' ),
__( 'Manage products and prices', 'sg-ai-studio' ),
__( 'Optimize for SEO', 'sg-ai-studio' ),
__( 'Do site maintenance', 'sg-ai-studio' ),
__( 'Run bulk actions with one prompt', 'sg-ai-studio' ),
__( 'One AI Agent.', 'sg-ai-studio' ),
__( 'Every WordPress task.', 'sg-ai-studio' ),
__( 'Turn hours of admin work into minutes of conversation.', 'sg-ai-studio' ),
__( 'GET STARTED', 'sg-ai-studio' ),
__( 'How can we improve?', 'sg-ai-studio' ),
__( 'Share your thoughts...', 'sg-ai-studio' ),
__( 'Close', 'sg-ai-studio' ),
__( 'Submit', 'sg-ai-studio' ),
__( '%(current)d of %(total)d', 'sg-ai-studio' ),
__( 'How satisfied are you with AI Agent for WordPress?', 'sg-ai-studio' ),
__( 'How satisfied are you with AI Agent for WordPress?', 'sg-ai-studio' ),
__( "Don't show again", 'sg-ai-studio' ),
__( 'Close', 'sg-ai-studio' ),
__( 'Next', 'sg-ai-studio' ),
__( 'Share your experience', 'sg-ai-studio' ),
__( 'Thank you for the rating! Leave a review on {{link}}wordpress.org{{/link}} to share your experience with other website owners.', 'sg-ai-studio' ),
__( 'Close', 'sg-ai-studio' ),
__( 'Submit review', 'sg-ai-studio' ),
__( 'Thank you for your feedback', 'sg-ai-studio' ),
__( 'We read every submission and use it to improve our product.', 'sg-ai-studio' ),
__( 'Close', 'sg-ai-studio' ),
__( 'You’re running low on tokens.', 'sg-ai-studio' ),
__( 'Upgrade to Plus', 'sg-ai-studio' ),
__( "You've run out of tokens.", 'sg-ai-studio' ),
__( 'Upgrade to Plus', 'sg-ai-studio' ),
__( "You're almost out of tokens.", 'sg-ai-studio' ),
__( 'Add tokens', 'sg-ai-studio' ),
__( "You've run out of tokens.", 'sg-ai-studio' ),
__( 'Add tokens', 'sg-ai-studio' ),
__( 'Drop Your Files Here To Upload', 'sg-ai-studio' ),
__( 'File Size up to: 20MB', 'sg-ai-studio' ),
__( 'Supported Formats: ', 'sg-ai-studio' ),
__( 'No results found.', 'sg-ai-studio' ),
__( 'Try different keywords, check spelling, or broaden your filters.', 'sg-ai-studio' ),
__( 'No conversations yet', 'sg-ai-studio' ),
__( 'Start chatting to build your history!', 'sg-ai-studio' ),
__( 'Start chat', 'sg-ai-studio' ),
__( 'Search...', 'sg-ai-studio' ),
__( 'Leave Anyway', 'sg-ai-studio' ),
__( 'Response still in progress', 'sg-ai-studio' ),
__( 'Leaving now will stop the response from finishing. You may lose the rest of the answer.', 'sg-ai-studio' ),
__( 'Are you sure you want to proceed?', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'Confirm', 'sg-ai-studio' ),
__( 'Add Token', 'sg-ai-studio' ),
__( 'Enable the connection to AI Studio by pasting your secret connection token.', 'sg-ai-studio' ),
__( 'Secret Connection Token', 'sg-ai-studio' ),
__( 'Token can not be empty.', 'sg-ai-studio' ),
__( 'cancel', 'sg-ai-studio' ),
__( 'save', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'Disconnect from AI Studio', 'sg-ai-studio' ),
__( 'Are you sure you want to proceed?', 'sg-ai-studio' ),
__( 'Power Mode is enabled', 'sg-ai-studio' ),
__( 'Power Mode is disabled', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again.', 'sg-ai-studio' ),
);
/* THIS IS THE END OF THE GENERATED FILE */