<?php
array(
__( "Ask me anything WordPress related and I'll help.", 'sg-ai-studio' ),
__( 'SiteGround AI Studio', 'sg-ai-studio' ),
__( 'New chat', 'sg-ai-studio' ),
__( 'History', 'sg-ai-studio' ),
__( 'Minimize', 'sg-ai-studio' ),
__( 'Today', 'sg-ai-studio' ),
__( 'Last 7 Days', 'sg-ai-studio' ),
__( 'Last 30 Days', 'sg-ai-studio' ),
__( 'Older', 'sg-ai-studio' ),
__( 'Open chat', 'sg-ai-studio' ),
__( 'A network error occurred. Please check your connection and try again.', 'sg-ai-studio' ),
__( 'Retry', 'sg-ai-studio' ),
__( 'User uploaded image', 'sg-ai-studio' ),
__( 'User uploaded image', 'sg-ai-studio' ),
__( 'Image had been deleted', 'sg-ai-studio' ),
__( 'File has been deleted', 'sg-ai-studio' ),
__( 'Image had been deleted', 'sg-ai-studio' ),
__( 'Power Mode is on. Note: Power Mode may modify your site’s content or settings. Tap Learn more for details before proceeding.', 'sg-ai-studio' ),
__( 'Learn more', 'sg-ai-studio' ),
__( 'Enable Power Mode to continue. Note: Power Mode may modify your site’s content or settings. Tap Learn more for details before enabling.', 'sg-ai-studio' ),
__( 'Learn more', 'sg-ai-studio' ),
__( 'Enable', 'sg-ai-studio' ),
__( 'You’re running low on tokens.', 'sg-ai-studio' ),
__( 'Upgrade to Plus', 'sg-ai-studio' ),
__( "You've run out of tokens.", 'sg-ai-studio' ),
__( 'Upgrade to Plus', 'sg-ai-studio' ),
__( 'You’re almost out of tokens.', 'sg-ai-studio' ),
__( 'Add tokens', 'sg-ai-studio' ),
__( "You've run out of tokens.", 'sg-ai-studio' ),
__( 'Add tokens', 'sg-ai-studio' ),
__( 'Drop Your Files Here To Upload', 'sg-ai-studio' ),
__( 'File Size up to: 20MB', 'sg-ai-studio' ),
__( 'Supported Formats: ', 'sg-ai-studio' ),
__( 'No results found.', 'sg-ai-studio' ),
__( 'Try different keywords, check spelling, or broaden your filters.', 'sg-ai-studio' ),
__( 'No conversations yet', 'sg-ai-studio' ),
__( 'Start chatting to build your history!', 'sg-ai-studio' ),
__( 'Start chat', 'sg-ai-studio' ),
__( 'Search...', 'sg-ai-studio' ),
__( 'Activity Log', 'sg-ai-studio' ),
__( '%(fromItem)d-%(toItem)d of %(totalItems)d', 'sg-ai-studio' ),
__( 'Go to first page', 'sg-ai-studio' ),
__( 'Go to previous page', 'sg-ai-studio' ),
__( 'Go to next page', 'sg-ai-studio' ),
__( 'Go to last page', 'sg-ai-studio' ),
__( 'Activity', 'sg-ai-studio' ),
__( 'Details', 'sg-ai-studio' ),
__( 'Date', 'sg-ai-studio' ),
__( 'AI Studio', 'sg-ai-studio' ),
__( 'Connect your WordPress site with the SiteGround AI Studio service. Chat with our AI agent to easily manage your WordPress site. Use the AI Studio text and image generative capabilities inside Gutenberg - experience the next-level editorial process.', 'sg-ai-studio' ),
__( 'Integration', 'sg-ai-studio' ),
__( 'Connected', 'sg-ai-studio' ),
__( 'Not Connected', 'sg-ai-studio' ),
__( 'Your plugin is connected to your SiteGround AI Studio service.', 'sg-ai-studio' ),
__( 'Your plugin is not linked to your SiteGround AI Studio service.', 'sg-ai-studio' ),
__( 'AI Studio Integration', 'sg-ai-studio' ),
__( 'Disconnect', 'sg-ai-studio' ),
__( 'Connect', 'sg-ai-studio' ),
__( 'Agent Settings', 'sg-ai-studio' ),
__( 'Supercharge AI Studio with Power Mode. Enable it to go beyond simple answers by executing complex, multi-step tasks and utilizing a broader set of capabilities and skills.', 'sg-ai-studio' ),
__( 'Learn More.', 'sg-ai-studio' ),
__( 'Power Mode', 'sg-ai-studio' ),
__( 'On', 'sg-ai-studio' ),
__( 'Off', 'sg-ai-studio' ),
__( 'Power Mode is enabled', 'sg-ai-studio' ),
__( 'Power Mode is disabled', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again.', 'sg-ai-studio' ),
__( 'Leave Anyway', 'sg-ai-studio' ),
__( 'Response still in progress', 'sg-ai-studio' ),
__( 'Leaving now will stop the response from finishing. You may lose the rest of the answer.', 'sg-ai-studio' ),
__( 'Are you sure you want to proceed?', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'Confirm', 'sg-ai-studio' ),
__( 'Add Token', 'sg-ai-studio' ),
__( 'Enable the connection to AI Studio by pasting your secret connection token.', 'sg-ai-studio' ),
__( 'Secret Connection Token', 'sg-ai-studio' ),
__( 'Token can not be empty.', 'sg-ai-studio' ),
__( 'cancel', 'sg-ai-studio' ),
__( 'save', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'Something went wrong. Please try again later.', 'sg-ai-studio' ),
__( 'Disconnect from AI Studio', 'sg-ai-studio' ),
__( 'Are you sure you want to proceed?', 'sg-ai-studio' ),
__( 'Select or search groups', 'sg-ai-studio' ),
__( 'Groups', 'sg-ai-studio' ),
__( 'Selected Groups', 'sg-ai-studio' ),
);
